### ISSUE TITLE
Adapt to Filterable BranchCreator

### ISSUE THREAD

**Issue by andrewkaufman** [Toolchefs/atomsGaffer#34]
Once https://github.com/GafferHQ/gaffer/issues/2917 is implemented, we may need to adapt the Generator node a bit to match.

**Comment by johnhaddon** [comment]
Removed the blocked label, since GafferHQ/gaffer#2917 is done, and available in the soon-to-be-released Gaffer 0.54. Give me a shout if you have any questions.

**Comment by andrewkaufman** [comment]
Just tested in Gaffer 0.54 and this seems to just work already without any code changes. :tada:
