### ISSUE TITLE
0.1.0: undefined symbol with 0.54.1.0 and 3.0.1

### ISSUE THREAD

**Issue by miniduck** [Toolchefs/atomsGaffer#40]
> AtomsCore::MetadataImpl<Imath_2_3::Box<Imath_2_3::Vec3<double> > >::toString(std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&) const

AtomsGaffer is built against 3.0.1 and  gaffer 0.54.1.0 with USE_GAFFER_DEPENDENCIES=ON

Building against 2.8.2 throws different undefined

> 2.8.2/0.54/lib/libAtomsGaffer.so: undefined symbol: _ZNK9AtomsCore18TypedArrayMetadataIN9Imath_2_34Vec3IdEEE7memSizeEv

> AtomsCore::TypedArrayMetadata<Imath_2_3::Vec3<double> >::memSize() const

Both of these are thrown on "import AtomsGaffer"

Any ideas what might be going on?

**Comment by andrewkaufman** [comment]
> Building against 2.8.2

I believe AtomsGaffer currently requires Atoms 3.0.0 at a minimum.

> AtomsGaffer is built against 3.0.1 and gaffer 0.54.1.0 with USE_GAFFER_DEPENDENCIES=ON

Can you clarify what Atoms distro you are using? At IE we're using the AtomsMaya download (but building with `USE_GAFFER_DEPENDENCIES=OFF`). I noticed AtomsMaya uses OpenEXR 2.2.0 whereas Gaffer dependencies uses OpenEXR 2.3.0. Can you confirm which version of exr your Atoms distro requires?

**Comment by miniduck** [comment]
Building against the houdini package, not sure which version of openexr that depends on..
I will try setting dependencies manually

Thank you

**Comment by miniduck** [comment]
Not much luck houdini package and 2.3...
Tried with Maya package and linking with the libs under 2018/3.0.1/lib
> GafferScene::SceneElementProcessor::computeProcessedBound(std::vector<IECore::InternedString, std::allocator<IECore::InternedString> > const&, Gaffer::Context const*, Imath_2_2::Box<Imath_2_2::Vec3<float> > const&) const
ldd states 2.2 is used and found
> libIex-2_2.so.12 => ../maya/2018/atoms/3.0.1/lib/libIex-2_2.so.12
> libImath-2_2.so.12 => ../maya/2018/atoms/3.0.1/lib/libImath-2_2.so.12

**Comment by miniduck** [comment]
Got a special atomscore build toolchefs built against gaffer 0.54 dependencies - that solved it
